<head>
    <link rel="stylesheet" type="text/css" href="http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/css/jquery.dataTables.css">
    <link href="/css/bootstrap.css" rel="stylesheet" />
</head>
<style>
    #table_id_filter{
        display: none;
    }
</style>
<body>
    <table id="table_id">
        <thead>
            <tr>
                <th>Sites</th>
                <th>Sites</th>
                <th>Sites</th>
                <th>Sites</th>
                <th>Sites</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
            </tr>
            <tr>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
            </tr>
            <tr>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
            </tr>
            <tr>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
            </tr>
            <tr>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
            </tr>
            <tr>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
            </tr>
            <tr>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
            </tr>
            <tr>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
            </tr>
            <tr>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
            </tr>
            <tr>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
            </tr>
            <tr>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
            </tr>
            <tr>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
            </tr>
            <tr>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
            </tr>
            <tr>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
            </tr>
            <tr>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
            </tr>
            <tr>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
            </tr>
            <tr>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
            </tr>

            <tr>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
                <td>SitePoint</td>
            </tr>

        </tbody>
    </table>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>

    <script>
        $(document).ready(function() {
            $('#table_id').DataTable();
        });
    </script>
</body>

</html>